all:
  hosts:
    k8s-master-node01: &id001
      ansible_host: 192.168.1.111
      ansible_ssh_private_key_file: /app/ansible/ssh_keys/id_ed25519
      ansible_user: ansible-user
      ansible_become: true
      ansible_become_method: sudo
      bootstrap_status: ready
    k8s-worker-node02: &id002
      ansible_host: 192.168.1.112
      ansible_ssh_private_key_file: /app/ansible/ssh_keys/id_ed25519
      ansible_user: ansible-user
      ansible_become: true
      ansible_become_method: sudo
      bootstrap_status: ready
    k8s-worker-node03: &id003
      ansible_host: 192.168.1.113
      ansible_ssh_private_key_file: /app/ansible/ssh_keys/id_ed25519
      ansible_user: ansible-user
      ansible_user: ansible-user
      ansible_become: true
      ansible_become_method: sudo
      bootstrap_status: ready
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o CheckHostIP=no
    kubecheck_path: /home/ansible-user/Kube-check
masters:
  hosts:
    k8s-master-node01: *id001
workers:
  hosts:
    k8s-worker-node02: *id002
    k8s-worker-node03: *id003
